### ISSUE TITLE
Crear Matriz RACI

### ISSUE THREAD

**Issue by Davibeh** [Davibeh/Switch_De_Distorcion_Ergonomico#1]
Esta tarea es para crear una Matriz RACI del proyecto.

**Comment by Davibeh** [comment]
[Matriz_RACI_CCTV_Fam_Martínez.xlsx - Matriz RACI-2.pdf](https://github.com/Davibeh/Switch_De_Distorcion_Ergonomico/files/1864971/Matriz_RACI_CCTV_Fam_Martinez.xlsx.-.Matriz.RACI-2.pdf)

**Archivo que muestra un ejemplo de una matriz RACI.**

**Comment by NoriegaGerardo** [comment]
[Raci.xlsx](https://github.com/Davibeh/Switch_De_Distorcion_Ergonomico/files/1865016/Raci.xlsx)

**Comment by Davibeh** [comment]
**Porfavor mover el issue a "in progress"**

[Raci_Comentarios_David_Bellomo.xlsx](https://github.com/Davibeh/Switch_De_Distorcion_Ergonomico/files/1865069/Raci_Comentarios_David_Bellomo.xlsx)

He agregado  un formato nuevo a tu matriz. Te quedó muy bien, solo hace falta coordinarse con Chung para agregar las Fases del proyecto. Basete un poco en el PDF que esta adjunto en esta conversación. 
Muy probablemente cuando agreguen las fases será requerido agregar mas actividades en tu columna "B"

**Comment by NoriegaGerardo** [comment]
[raciv2.xlsx](https://github.com/Davibeh/Switch_De_Distorcion_Ergonomico/files/1865805/raciv2.xlsx)
ya agrege las partes del pdf @EdgarChung ve si puedes agregar las fases en tu issue
