### ISSUE TITLE
Creación del WBS

### ISSUE THREAD

**Issue by Davibeh** [Davibeh/Switch_De_Distorcion_Ergonomico#4]
Crear el WBS para el proyecto de las actividades que se realizaron en el desarrollo del proyecto.  
Coordinarse con Gerardo cuando se cree la Matriz RACI, ya que las actividades a realizar están ligadas  alas actividades en el WBS.
Usar archivo adjunto de ejemplo.
Crear el diagrama en https://www.draw.io/ y exportarlo como .html.

**Comment by Davibeh** [comment]
[Visio-WBS_INSTALACION Y PUES EN SERVICIO DE UN SISTEMA DE CCTV PARA SEGURIDAD DOMESTICA.vsdx.pdf](https://github.com/Davibeh/Switch_De_Distorcion_Ergonomico/files/1864965/Visio-WBS_INSTALACION.Y.PUES.EN.SERVICIO.DE.UN.SISTEMA.DE.CCTV.PARA.SEGURIDAD.DOMESTICA.vsdx.pdf)

**Comment by EdgarChung** [comment]
[wbs pedal.pptx](https://github.com/Davibeh/Switch_De_Distorcion_Ergonomico/files/1865048/wbs.pedal.pptx)

**Comment by Davibeh** [comment]
Porfavor mover el issue a "In Progress".

Las actividades van orientadas a la parte técnica pero es necesario que agregues las actividades que se hicieron de compras analisis y pruebas.

**Comment by EdgarChung** [comment]
[wbs pedal.pptx](https://github.com/Davibeh/Switch_De_Distorcion_Ergonomico/files/1866052/wbs.pedal.pptx)
ya quedo

**Comment by Davibeh** [comment]
Te quedó excelente lo subiré al proyecto en brevé. Mcuhas gracias ya estamos mas cerca del éxito.
