### ISSUE TITLE
Efecto Distorción no funciona

### ISSUE THREAD

**Issue by Davibeh** [Davibeh/Switch_De_Distorcion_Ergonomico#9]
Al parecer el efecto distorción no funciona con el nuevo sistema. 
La razón es que el  el voltaje leido no alcanza el valor  limite esperado ( 4090 -wMaxParameter) 
con un wMaxParameter de 500.   

¿Podrías analizarlo y verificar si es necesario algún tipo de calibración al valor wMaxParameter?

**Comment by EdgarChung** [comment]
El max parameter se modica, dependiendo del nivel de distorcion que se quiere, 0 no hay distorcion y mas 1200 se escucharia casi pura distorcion
